name: Deploy para Locaweb via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Instalar Dependências
        run: npm install

      - name: Build do Projeto React
        run: npm run build
        env:
          REACT_APP_Maps_API_KEY: ${{ secrets.REACT_APP_Maps_API_KEY }}
          REACT_APP_UPLOADCARE_PUBLIC_KEY: ${{ secrets.REACT_APP_UPLOADCARE_PUBLIC_KEY}}
          REACT_APP_FORMSPREE_ID_CONTATO: ${{ secrets.REACT_APP_FORMSPREE_ID_CONTACT }}
          REACT_APP_FORMSPREE_ID_TRABALHE_CONOSCO: ${{ secrets.REACT_APP_FORMSPREE_ID_WORK}}

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "build"
